//import js for webpack
import { handleSubmit, updateUI, createInput, reset } from './js/formHandler'

//import styles for webpack
import './styles/resets.scss'
import './styles/base.scss'
import './styles/footer.scss'
import './styles/form.scss'
import './styles/header.scss'

//images
import './media/images/Postcardyourfuture.png'
import './media/images/postcard-back.jpg'
import './media/icons/a01d.png'
import './media/icons/a01n.png'
import './media/icons/a02d.png'
import './media/icons/a02n.png'
import './media/icons/a03d.png'
import './media/icons/a03n.png'
import './media/icons/a04d.png'
import './media/icons/a04n.png'
import './media/icons/a05d.png'
import './media/icons/a05n.png'
import './media/icons/a06d.png'
import './media/icons/a06n.png'
import './media/icons/c01d.png'
import './media/icons/c01n.png'
import './media/icons/c02d.png'
import './media/icons/c02n.png'
import './media/icons/c03d.png'
import './media/icons/c03n.png'
import './media/icons/c04d.png'
import './media/icons/c04n.png'
import './media/icons/d01d.png'
import './media/icons/d01d.png'
import './media/icons/d02d.png'
import './media/icons/d02n.png'
import './media/icons/d03d.png'
import './media/icons/d03n.png'
import './media/icons/f01d.png'
import './media/icons/f01n.png'
import './media/icons/r01d.png'
import './media/icons/r01n.png'
import './media/icons/r02d.png'
import './media/icons/r02n.png'
import './media/icons/r03d.png'
import './media/icons/r03n.png'
import './media/icons/r04d.png'
import './media/icons/r04n.png'
import './media/icons/r05d.png'
import './media/icons/r05n.png'
import './media/icons/r06d.png'
import './media/icons/r06n.png'
import './media/icons/s01d.png'
import './media/icons/s01n.png'
import './media/icons/s02d.png'
import './media/icons/s02n.png'
import './media/icons/s03d.png'
import './media/icons/s03n.png'
import './media/icons/s04d.png'
import './media/icons/s04n.png'
import './media/icons/s05d.png'
import './media/icons/s05n.png'
import './media/icons/s06d.png'
import './media/icons/s06n.png'
import './media/icons/t01d.png'
import './media/icons/t01n.png'
import './media/icons/t02d.png'
import './media/icons/t02n.png'
import './media/icons/t03d.png'
import './media/icons/t03n.png'
import './media/icons/t04d.png'
import './media/icons/t04n.png'
import './media/icons/t05d.png'
import './media/icons/t05n.png'
import './media/icons/u00d.png'
import './media/icons/u00n.png'

export {
    handleSubmit,
    updateUI,
    createInput,
    reset
}